services:
  - type: web
    name: dashboard
    env: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: dashboard/dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
